### ISSUE TITLE
PWA(Progressive Web Application) 적용하기

### ISSUE THREAD

**Issue by Dokyeongyun** [Dokyeongyun/HoneyPots-web#1]
**Problem or enhancements and It's Background**
- 현재 애플리케이션을 이용하기 위해서는 브라우저에서 도메인 주소를 직접 입력하여 접속해야한다.
- 이는 접근성이 떨어져 사용자 참여를 유도하기 힘들다.
- [PWA](https://developer.mozilla.org/ko/docs/Web/Progressive_web_apps/Introduction)를 적용하여 애플리케이션 형태로 다운로드가 가능하도록 하자

**Solutions**
- PWA 적용하기

**TODO Tasks**
- [x] `next.js` 프로젝트에 `PWA`적용 위한 패키지 추가
- [x] icon, favicon 파일 추가 및 `manifest.json` 작성
- [x] Service Worker 등록
- [x] 데스크탑 및 모바일 브라우저에서 PWA 설치 가능 여부 확인

**Reference**
- https://developer.mozilla.org/ko/docs/Web/Progressive_web_apps/Introduction
- https://developer.mozilla.org/ko/docs/Web/Progressive_web_apps/Installable_PWAs

**Comment by Dokyeongyun** [comment]
- Chrome 개발자 도구에서 확인 PWA 적용 여부
![image](https://user-images.githubusercontent.com/61186671/189530244-b5352d80-05c6-4735-b06e-50650ab9e78b.png)
