### ISSUE TITLE
Push notification click listener 생성

### ISSUE THREAD

**Issue by Dokyeongyun** [Dokyeongyun/HoneyPots-web#19]
**Problem or enhancements and It's Background**
- 현재 사용자 활동에 대한 알림이 전송되지만, 해당 알림을 클릭하여도 아무 동작도 하지 않는다.
- 알림과 관련된 페이지로 전환하여 사용자의 참여를 향상시킬 수 있도록 하자.

**Solutions**
- Push notification click listener 생성하여 알림과 관련된 페이지로 전환하기

**TODO Tasks**
- [ ] 기존 FCM 관련 로직 리팩터링
- [ ] BE 서버에서 전송해주는 Notification Payload의 `click_action` 으로 페이지 전환하기
- [ ] Foreground, Background 모두에서 동작 확인

**Comment by Dokyeongyun** [comment]
**Reference**
- service worker 파일 수정 시, 재설치가 되지 않으므로 update 처리하기 
  - https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/update
